version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: viio
    ports:
      - 3001:5432
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 5000:5000
