const ACTION_TYPES = {
    POST_LOGIN_REQUEST: "POST_LOGIN_REQUEST",
    POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
    POST_LOGIN_FAILURE: "POST_LOGIN_FAILURE",
    CLEAR_LOGIN_DATA: "CLEAR_LOGIN_DATA",
    POST_REGISTER_REQUEST: "POST_REGISTER_REQUEST",
    POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
    POST_REGISTER_FAILURE: "POST_REGISTER_FAILURE",
}

export default ACTION_TYPES
