const ACTION_TYPES = {
    POST_LOGIN_REQUEST: "POST_LOGIN_REQUEST",
    POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
    POST_LOGIN_FAILURE: "POST_LOGIN_FAILURE",
    CLEAR_LOGIN_DATA: "CLEAR_LOGIN_DATA",
    POST_REGISTER_REQUEST: "POST_REGISTER_REQUEST",
    POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
    POST_REGISTER_FAILURE: "POST_REGISTER_FAILURE",
    CLEAR_REGISTER_DATA: "CLEAR_REGISTER_DATA",
    VERIFY_JWT_REQUEST: "VERIFY_JWT_REQUEST",
    VERIFY_JWT_SUCCESS: "VERIFY_JWT_SUCCESS",
    VERIFY_JWT_FAILURE: "VERIFY_JWT_FAILURE",
    CLEAR_JWT: "CLEAR_JWT",
}

export default ACTION_TYPES
