const ACTION_TYPES = {
    POST_LOGIN_REQUEST: "POST_LOGIN_REQUEST",
    POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
    POST_LOGIN_FAILURE: "POST_LOGIN_FAILURE",
    CLEAR_LOGIN_DATA: "CLEAR_LOGIN_DATA",
}

export default ACTION_TYPES
